apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-crud-deployment
spec:
  selector:
    matchLabels:
      app: node-k8s-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: node-k8s-mysql
    spec:
      containers:
        - name: node-crud-k8s
          image: jdkz/otus-dz2:v1
          ports:
            - containerPort: 8000
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: node-crud-svc
spec:
  selector:
    app: node-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8000 # The port that the service is running on in the cluster
      targetPort: 8000 # The port exposed by the service
  type: NodePort # type of the service.

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "arch.homework"
    http:
      paths:
        - path: /health
          pathType: Prefix
          backend:
            service:
              name: node-crud-svc
              port:
                number: 8000
        - path: /users
          pathType: Prefix
          backend:
            service:
              name: node-crud-svc
              port:
                number: 8000