apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username:  {{ .Values.mysql.username | b64enc | quote }}
  password:  {{ .Values.mysql.user_password | b64enc | quote }}